apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: speaker-deployment
      annotations:
        prometheus.io.scrape: "true"
    spec:
      containers:
      - name: microservice-speaker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
          - containerPort: 9080
        imagePullPolicy: IfNotPresent
        env:
          - name: isAppDown
            valueFrom:
              configMapKeyRef:
                name: appdown
                key: appdown
          - name: USERNAME
            value: admin
          - name: PASSWORD
            value: password
          - name: MB_KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mb-keystore-password
                key: password
          - name: MB_TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mb-truststore-password
                key: password
{{ end }}
        readinessProbe:
          httpGet:
            path: /speaker/nessProbe
            port: 9080
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 120
          periodSeconds: 15
{{ if ne .Values.test true }}
        volumeMounts:
        - name: keystore
          mountPath: /etc/wlp/config/keystore
        - name: truststore
          mountPath: /etc/wlp/config/truststore
        - name: liberty-config
          mountPath: /config/configDropins
      volumes:
      - name: keystore
        secret:
          secretName: mb-keystore
      - name: truststore
        secret:
          secretName: mb-truststore
      - name: liberty-config
        configMap:
          name: liberty-logging-config
          items:
            - key: keystore.xml
              path: defaults/keystore.xml
            - key: logging.xml
              path: defaults/logging.xml
          optional: true
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: speaker-service
spec:
  ports:
    - port: 9080
  selector:
    name: speaker-deployment
